name = "artic-eval-v2"
pages_build_output_dir = "public"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "artic_eval_db"
database_id = "a62ee690-1dc6-484c-aa47-a5bb42820ef0"
preview_database_id = "DB"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "artic_eval_db", database_id = "a62ee690-1dc6-484c-aa47-a5bb42820ef0" }
]

[env.preview]
d1_databases = [
  { binding = "DB", database_name = "artic_eval_db", database_id = "a62ee690-1dc6-484c-aa47-a5bb42820ef0" }
]

[[env.production.vars]]
ENVIRONMENT = "production"

[[env.preview.vars]]
ENVIRONMENT = "preview"