name = "iplc-articulation-eval"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "public"

# Production environment configuration
# Note: Bindings with actual resource IDs should be configured here when available
# [env.production]
# [[env.production.kv_namespaces]]
# binding = "SESSION_STORE"
# id = "your-kv-namespace-id"
#
# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "iplc-articulation-db"
# database_id = "your-d1-database-id"

# Local development configuration
[env.development]
# KV namespace for local development
[[env.development.kv_namespaces]]
binding = "SESSION_STORE"
preview_id = ""

# D1 database for local development
[[env.development.d1_databases]]
binding = "DB"
database_name = "iplc-articulation-db-dev"
database_id = ""

# Pages build configuration
[build]
command = "node build.js"
cwd = "."
watch_dir = "public"

# Local development settings
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"