name = "articeval"
compatibility_date = "2025-07-01"
pages_build_output_dir = "public"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Database binding for form data storage
[[d1_databases]]
binding = "DB"
database_name = "iplc-eval-db"
database_id = "690d60be-7ba3-4a2c-8de9-4cd8f034430e"

# Production environment
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "iplc-eval-db"
database_id = "690d60be-7ba3-4a2c-8de9-4cd8f034430e"