name = "articeval"
compatibility_date = "2024-12-01"
pages_build_output_dir = "public"
compatibility_flags = ["nodejs_compat"]

# Top-level bindings for local development and default environment
[[d1_databases]]
binding = "DB"
database_name = "iplc-eval-db"
database_id = "690d60be-7ba3-4a2c-8de9-4cd8f034430e"

[[kv_namespaces]]
binding = "SESSIONS"
id = "786a335542bf4f758fb3d7ad13b21ba9"

# Preview environment configuration
[env.preview]
[[env.preview.kv_namespaces]]
binding = "SESSIONS"
id = "33d19a17dee0462480c70d093aacfce"

# Production environment uses same bindings as top-level
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "iplc-eval-db"
database_id = "690d60be-7ba3-4a2c-8de9-4cd8f034430e"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "786a335542bf4f758fb3d7ad13b21ba9"

# JWT_SECRET should be configured in Cloudflare Pages dashboard
[env.production.vars]
# Add any production-specific environment variables here