name = "articeval"
compatibility_date = "2024-12-01"
pages_build_output_dir = "public"
compatibility_flags = ["nodejs_compat"]

[env.production]
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production-2024"

[[env.production.d1_databases]]
binding = "DB"
database_name = "iplc-eval-db"
database_id = "690d60be-7ba3-4a2c-8de9-4cd8f034430e"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "786a335542bf4f758fb3d7ad13b21ba9"
preview_id = "33d19a17dee0462480c70d093aacfce"